default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "1.1.0"
    hooks:
      - id: sync_with_poetry

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.3.3"
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: bot/photo/
        exclude_types:
          - markdown
      - id: check-added-large-files
        args:
          - "--maxkb=1024"
      - id: check-yaml
        exclude: \.gitlab-ci.yml
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"
          - "--install-types"
          - "--non-interactive"
        exclude: "alembic/"
        additional_dependencies:
          - annotated-types==0.6.0 ; python_version >= "3.11" and python_version < "4.0"
          - cfgv==3.4.0 ; python_version >= "3.11" and python_version < "4.0"
          - colorama==0.4.6 ; python_version >= "3.11" and python_version < "4.0" and sys_platform == "win32"
          - coverage==7.5.1 ; python_version >= "3.11" and python_version < "4.0"
          - dependency-injector==4.41.0 ; python_version >= "3.11" and python_version < "4.0"
          - distlib==0.3.8 ; python_version >= "3.11" and python_version < "4.0"
          - filelock==3.14.0 ; python_version >= "3.11" and python_version < "4.0"
          - identify==2.5.36 ; python_version >= "3.11" and python_version < "4.0"
          - iniconfig==2.0.0 ; python_version >= "3.11" and python_version < "4.0"
          - mypy-extensions==1.0.0 ; python_version >= "3.11" and python_version < "4.0"
          - mypy==1.10.0 ; python_version >= "3.11" and python_version < "4.0"
          - nodeenv==1.8.0 ; python_version >= "3.11" and python_version < "4.0"
          - packaging==24.0 ; python_version >= "3.11" and python_version < "4.0"
          - platformdirs==4.2.2 ; python_version >= "3.11" and python_version < "4.0"
          - pluggy==1.5.0 ; python_version >= "3.11" and python_version < "4.0"
          - pre-commit==3.7.1 ; python_version >= "3.11" and python_version < "4.0"
          - pyaes==1.6.1 ; python_version >= "3.11" and python_version < "4.0"
          - pydantic-core==2.18.2 ; python_version >= "3.11" and python_version < "4.0"
          - pydantic-settings==2.2.1 ; python_version >= "3.11" and python_version < "4.0"
          - pydantic==2.7.1 ; python_version >= "3.11" and python_version < "4.0"
          - pyrogram==2.0.106 ; python_version >= "3.11" and python_version < "4.0"
          - pysocks==1.7.1 ; python_version >= "3.11" and python_version < "4.0"
          - pytest==7.4.4 ; python_version >= "3.11" and python_version < "4.0"
          - python-dotenv==1.0.1 ; python_version >= "3.11" and python_version < "4.0"
          - pyyaml==6.0.1 ; python_version >= "3.11" and python_version < "4.0"
          - ruff==0.3.7 ; python_version >= "3.11" and python_version < "4.0"
          - setuptools==69.5.1 ; python_version >= "3.11" and python_version < "4.0"
          - six==1.16.0 ; python_version >= "3.11" and python_version < "4.0"
          - tgcrypto==1.2.5 ; python_version >= "3.11" and python_version < "4.0"
          - typing-extensions==4.11.0 ; python_version >= "3.11" and python_version < "4.0"
          - virtualenv==20.26.2 ; python_version >= "3.11" and python_version < "4.0"
