from typing import Final


START: Final[str] = "AgACAgIAAxkDAAIR72UVIJEhUNYHdVnzYNHaV-uZszJqAAKazjEb8f2pSNj2NVwwo5X4AAgBAAMCAAN3AAceBA"

KAS: Final[str] = "AgACAgIAAxkDAAIR72UVIJEhUNYHdVnzYNHaV-uZszJqAAKazjEb8f2pSNj2NVwwo5X4AAgBAAMCAAN3AAceBA"

SOUTH: Final[str] = "AgACAgIAAxkBAANLZSvw6sbbhtC0piS-niVsbUUwhBYAAvzTMRv6Q2FJ0-vPxZzecTgACAEAAwIAA3kABx4E"
