from typing import Final


START: Final[str] = "AgACAgIAAxkBAAN9ZSzxtqf-DdXABlTla9F163DgovcAAsHMMRuCsWhJZOvJD5p2lIwACAEAAwIAA3kABx4E"

KAS: Final[str] = "AgACAgIAAxkBAANqZSv8bICTxUkI9o2PHUc5gIbExA0AAk7VMRv6Q2FJNtsdFthY-JMACAEAAwIAA3kABx4E"

SOUTH: Final[str] = "AgACAgIAAxkBAANfZSv69YuiNNcrZisDlhrnPexR8_oAAkvVMRv6Q2FJ_VkYnfxZuacACAEAAwIAA3kABx4E"
