from typing import Final


START: Final[str] = "AgACAgIAAxkBAAIBNGUunpMnVMnESPWmeXWVclY0raVZAAIlzTEbJqZ4STbl24-6RWn6AAgBAAMCAAN5AAceBA"

KAS: Final[str] = "AgACAgIAAxkBAAIBOmUunt-VOlzBefm0WvfaYuAAATvLAAPozDEbt114ST1kDNBKXafLAAgBAAMCAAN5AAceBA"

SOUTH: Final[str] = "AgACAgIAAxkBAAIBN2UunszXDxOIzJFKVdc_iI3bYDBCAAIozTEbJqZ4STbCmmuAmk7LAAgBAAMCAAN5AAceBA"
